CREATE DATABASE pasabd;
CREATE USER 'pasausu'@'%' IDENTIFIED BY 'pasapass';
GRANT ALL PRIVILEGES
  ON pasabd.*
  TO 'pasausu'@'%';
FLUSH PRIVILEGES;
USE pasabd;
CREATE TABLE PASATIEMPO (
  PAS_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  PAS_NOMBRE VARCHAR(255) NOT NULL,
  CONSTRAINT PAS_U_NOMBRE UNIQUE(PAS_NOMBRE)
)
CHARSET = utf8
COLLATE = utf8_spanish_ci
ENGINE = InnoDB;